{
 "bad": [
  "Exception",
  "TypeError",
  "__import__",
  "continuation",
  "hasattr",
  "isinstance",
  "len",
  "object",
  "property",
  "self",
  "self.concurrent_future",
  "self.concurrent_future.done",
  "self.concurrent_future.result",
  "self.concurrent_future.set_exception",
  "self.concurrent_future.set_running_or_notify_cancel",
  "self.func",
  "self.future",
  "self.future.__iter__",
  "self.future._loop.call_soon_threadsafe",
  "self.future.done",
  "self.future.result",
  "self.future.set_result",
  "staticmethod"
 ],
 "deps": [
  [
   "typing-3.5.0.1-py34_0",
   "typing-3.6.1-py35_0",
   "typing-3.6.2-py36_0",
   "typing-3.6.4-py27_0",
   "typing-3.6.6-py27_0",
   "typing-3.6.6-py35_0"
  ],
  [
   "unsync-1.2.1-pyh9f0ad1d_0"
  ]
 ]
}