{
 "bad": [
  "_compat.urllib.Request",
  "_compat.urllib.build_opener",
  "_compat.urllib.urlopen",
  "annotated_text.AnnotatedTextHandler.parse",
  "contextlib.ignored",
  "document_from_fragment",
  "getter",
  "getter.__doc__",
  "getter.__module__",
  "getter.__name__",
  "hashlib.md5",
  "itertools.groupby",
  "lxml.etree.XMLSyntaxError",
  "lxml.etree.tostring",
  "lxml.etree.tounicode",
  "object.decode",
  "object.encode",
  "os.mkdir",
  "os.path.dirname",
  "os.path.exists",
  "os.path.join",
  "os.path.pardir",
  "re.IGNORECASE",
  "re.UNICODE",
  "sys.version_info",
  "urllib2"
 ],
 "deps": {
  "__future__": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "_compat": [],
  "annotated_text": [],
  "chardet": [
   "google-cloud-bigquery-storage-core/conda-forge/noarch/google-cloud-bigquery-storage-core-2.0.0-pyh9f0ad1d_1"
  ],
  "contextlib": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "copy": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "docopt": [
   "docopt/conda-forge/noarch/docopt-0.6.2-py_1"
  ],
  "document_from_fragment": [],
  "getter": [],
  "hashlib": [],
  "itertools": [],
  "locale": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "logging": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "lxml": [
   "pyexcel-ods3/conda-forge/noarch/pyexcel-ods3-0.5.3-py_0"
  ],
  "object": [],
  "operator": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "os": [],
  "pkg_resources": [
   "setuptools/conda-forge/linux-64/setuptools-41.2.0-py27_0"
  ],
  "pprint": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "re": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "sys": [],
  "tempfile": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "urllib": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ],
  "urllib2": [],
  "webbrowser": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython"
  ]
 }
}