{
 "bad": [
  "py.path.local",
  "pytest.ExitCode.OK",
  "pytest.ExitCode.TESTS_FAILED",
  "sys",
  "sys.platform",
  "sys.pypy_version_info",
  "sys.stdout",
  "time",
  "time.time"
 ],
 "deps": {
  "__future__": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004",
   "python/conda-forge/linux-64/python-3.7.10-hffdb5ce_100_cpython"
  ],
  "_pytest": [
   "pytest/conda-forge/linux-64/pytest-3.2.0-py35_0",
   "pytest/conda-forge/linux-64/pytest-3.6.3-py36_0",
   "pytest/conda-forge/linux-64/pytest-3.7.2-py35_0",
   "pytest/conda-forge/linux-64/pytest-3.7.4-py35_0",
   "pytest/conda-forge/linux-64/pytest-4.3.1-py36_0",
   "pytest/conda-forge/linux-64/pytest-4.6.0-py37_0",
   "pytest/conda-forge/linux-64/pytest-4.6.3-py27_0"
  ],
  "platform": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004",
   "python/conda-forge/linux-64/python-3.7.10-hffdb5ce_100_cpython"
  ],
  "pluggy": [
   "pluggy/conda-forge/noarch/pluggy-0.10.0-py_0",
   "pluggy/conda-forge/noarch/pluggy-0.12.0-py_0",
   "pluggy/conda-forge/noarch/pluggy-0.6.0-py_0"
  ],
  "py": [
   "py/conda-forge/noarch/py-1.6.0-py_0",
   "py/conda-forge/noarch/py-1.8.1-py_0",
   "py/conda-forge/noarch/py-1.8.2-pyh9f0ad1d_0"
  ],
  "pytest": [
   "pytest/conda-forge/linux-64/pytest-6.0.2-py36hc560c46_0",
   "pytest/conda-forge/linux-64/pytest-6.1.1-py37hc8dfbb8_0"
  ],
  "sys": [],
  "time": []
 }
}