{
 "bad": [
  "django.conf.settings.DATABASE_CONNECTION_POOLING",
  "django.conf.settings.USE_TZ",
  "django.db.backends.base.schema.logger.debug",
  "django.db.connections.cursor",
  "django.db.models.Index",
  "django.db.models.Index.suffix",
  "django.db.models.indexes.Index.suffix",
  "django.utils.deprecation.RemovedInDjango21Warning",
  "itertools.chain",
  "itertools.chain.from_iterable",
  "pyodbc",
  "pyodbc.Error",
  "pyodbc.SQL_BIGINT",
  "pyodbc.SQL_BIT",
  "pyodbc.SQL_CHAR",
  "pyodbc.SQL_DECIMAL",
  "pyodbc.SQL_DOUBLE",
  "pyodbc.SQL_DRIVER_NAME",
  "pyodbc.SQL_DRIVER_VER",
  "pyodbc.SQL_FLOAT",
  "pyodbc.SQL_GUID",
  "pyodbc.SQL_INTEGER",
  "pyodbc.SQL_LONGVARBINARY",
  "pyodbc.SQL_NUMERIC",
  "pyodbc.SQL_REAL",
  "pyodbc.SQL_SMALLINT",
  "pyodbc.SQL_SS_TIME2",
  "pyodbc.SQL_TINYINT",
  "pyodbc.SQL_TYPE_DATE",
  "pyodbc.SQL_TYPE_TIME",
  "pyodbc.SQL_TYPE_TIMESTAMP",
  "pyodbc.SQL_VARBINARY",
  "pyodbc.SQL_VARCHAR",
  "pyodbc.SQL_WCHAR",
  "pyodbc.SQL_WLONGVARCHAR",
  "pyodbc.SQL_WVARCHAR",
  "pyodbc.connect",
  "pyodbc.pooling",
  "pyodbc.version",
  "qn",
  "time",
  "time.sleep"
 ],
 "deps": {
  "binascii": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ],
  "datetime": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ],
  "django": [
   "django/conda-forge/linux-64/django-3.0.4-py36_0",
   "django/conda-forge/noarch/django-3.1.4-pyhd8ed1ab_0",
   "django/conda-forge/noarch/django-3.2-pyhd8ed1ab_0"
  ],
  "itertools": [],
  "os": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ],
  "pyodbc": [],
  "pytz": [
   "google-cloud-bigquery-storage-core/conda-forge/noarch/google-cloud-bigquery-storage-core-2.0.0-pyh9f0ad1d_1",
   "pytz/conda-forge/linux-64/pytz-2017.3-py35_3",
   "pytz/conda-forge/linux-64/pytz-2017.3-py36_0",
   "pytz/conda-forge/noarch/pytz-2018.4-py_0",
   "pytz/conda-forge/noarch/pytz-2019.3-py_0"
  ],
  "qn": [],
  "re": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ],
  "subprocess": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ],
  "time": [],
  "types": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ],
  "uuid": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ],
  "warnings": [
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_0_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h4d41432_2_cpython",
   "python/conda-forge/linux-64/python-3.6.7-h381d211_1004"
  ]
 }
}