{
 "bad": [
  "ClientException",
  "Exception",
  "MemcachePool",
  "ValidationException",
  "bytearray",
  "bytes",
  "collections.namedtuple",
  "func",
  "int",
  "isinstance",
  "len",
  "object",
  "set",
  "str",
  "super",
  "tuple"
 ],
 "deps": [
  [
   "aiomcache-0.6.0-py_0"
  ]
 ]
}