{
 "bad": [
  "_kwargs_get",
  "boto.log.debug",
  "boto.log.error",
  "exception_class",
  "urllib.urlencode"
 ],
 "deps": {
  "boto": [
   "boto/conda-forge/noarch/boto-2.49.0-py_0"
  ],
  "json": [
   "python/conda-forge/linux-64/python-3.5.4-0",
   "python/conda-forge/linux-64/python-3.5.4-3",
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h425cb1d_0_cpython",
   "python/conda-forge/linux-64/python-3.6.6-h5001a0f_3",
   "python/conda-forge/linux-64/python-3.6.7-h357f687_1006",
   "python/conda-forge/linux-64/python-3.7.1-h381d211_1003",
   "python/conda-forge/linux-64/python-3.7.6-h357f687_3_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_8_cpython",
   "python/conda-forge/linux-64/python-3.8.6-hffdb5ce_5_cpython",
   "python/conda-forge/linux-64/python-3.9.0-h2a148a8_4_cpython"
  ],
  "os": [
   "python/conda-forge/linux-64/python-3.5.4-0",
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.6.11-h425cb1d_0_cpython",
   "python/conda-forge/linux-64/python-3.6.6-h5001a0f_3",
   "python/conda-forge/linux-64/python-3.6.7-h357f687_1006",
   "python/conda-forge/linux-64/python-3.7.1-h381d211_1003",
   "python/conda-forge/linux-64/python-3.7.6-h357f687_3_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_8_cpython",
   "python/conda-forge/linux-64/python-3.9.0-h2a148a8_4_cpython"
  ],
  "urllib": [
   "python/conda-forge/linux-64/python-3.5.4-0",
   "python/conda-forge/linux-64/python-3.6.10-he5300dc_1011_cpython",
   "python/conda-forge/linux-64/python-3.6.6-h5001a0f_3",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_6_cpython",
   "python/conda-forge/linux-64/python-3.8.5-h1103e12_8_cpython",
   "python/conda-forge/linux-64/python-3.9.0-h2a148a8_4_cpython"
  ]
 }
}