{
 "bad": [
  "AttributeError",
  "Cache",
  "Cache.from_json",
  "Exception",
  "Exception.__init__",
  "IOError",
  "ImportError",
  "Item",
  "ItemGroup",
  "ItemList",
  "KeyError",
  "ValueError",
  "dict",
  "isinstance",
  "len",
  "list",
  "object",
  "open",
  "print",
  "requests_oauthlib.OAuth2Session",
  "staticmethod",
  "str",
  "urllib.urlencode"
 ],
 "deps": [
  [
   "oauthlib-2.0.1-py36_0",
   "oauthlib-2.0.4-py_0",
   "oauthlib-2.0.6-py_0",
   "oauthlib-2.0.7-py_0",
   "oauthlib-2.1.0-py_0",
   "oauthlib-3.0.1-py_0"
  ],
  [
   "pyalveo-1.0.5-py_0"
  ]
 ]
}